apiVersion: v1
kind: Service
metadata:
  name: elastic-agent-tcp
  namespace: kube-system
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: elastic-agent
  ports:
    - name: tcp-8090
      protocol: TCP
      port: 8090
      targetPort: 8090
      nodePort: 30090
